# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7c5de8de-05e3-44a7-bbd4-76f5aa2d1c24";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a872b0b7-5df6-4dd2-b1a9-5945e57a1acc".device =
    "/dev/disk/by-uuid/a872b0b7-5df6-4dd2-b1a9-5945e57a1acc";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2AC6-811A";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/bd8f538e-c3c0-44be-988f-4df6c32c6f56"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
