name: Check formatting
run-name: ${{ forgejo.actor }} is checking the code formatting
on: [push]
jobs:
  ensure-formatting:
    runs-on: nix
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}
      - name: Format and Lint
        run: nix fmt -- --ci
