# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e634c64a-9151-4cf3-8a6b-6e01318cab20";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/FB18-FCBB";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/865d6c84-4350-4a87-a0b7-3d2500903f2c"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with networking.interfaces.<interface>.useDHCP.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-82ab894f33de.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth03e13e6.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2f0a5c2.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5c54e01.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7d67e01.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8d21a1e.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethaad837e.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb5471e7.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethd78cbeb.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethd8e9564.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp10s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
