"""Static category definitions.

Every anchor entry is a list of strings. The *first* element is the
canonical display form (used as-is — properly capitalized German with
correct casing for compounds, brand names, multi-word phrases). Any
remaining elements are alternate matchable forms — typos, STT
garbles, lower-case shortcuts, related sub-products — that all
resolve to the index-0 form on display.

  ["Apfel"]                                 — single-form anchor
  ["Süßstoff", "süßstofftabletten", ...]    — fold variants under one
  ["Rotkohl im Glas", "rotkohl glas"]       — multi-word with explicit casing

The classifier embeds each form separately; ``matched_anchor`` on the
resulting Match is always the canonical (index 0) form.

Print order is decided elsewhere (Nix config); this file only declares
which categories exist and their semantic surface forms.
"""

CATEGORIES: list[tuple[str, list[list[str]]]] = [
    (
        "Obst",
        [
            ["Apfel", "äpfel"],
            ["Banane", "bananen"],
            ["Birne", "birnen"],
            ["Trauben", "weintrauben"],
            ["Orange", "orangen"],
            ["Mandarine"],
            ["Clementine"],
            ["Zitronen", "zitrone"],
            ["Limetten", "limette"],
            ["Grapefruit"],
            ["Erdbeere", "erdbeeren"],
            ["Blaubeere", "heidelbeere"],
            ["Himbeere", "himbeeren"],
            ["Brombeere"],
            ["Johannisbeere"],
            ["Stachelbeere", "stachelbeeren"],
            ["Kirsche", "kirschen"],
            ["Pflaume", "pflaumen"],
            ["Mirabelle"],
            ["Ananas"],
            ["Melone"],
            ["Wassermelone", "wasser milune"],
            ["Honigmelone"],
            ["Galiamelone"],
            ["Mango"],
            ["Papaya"],
            ["Pfirsich"],
            ["Nektarine"],
            ["Aprikose"],
            ["Kiwi"],
            ["Feige"],
            ["Granatapfel"],
            ["Datteln"],
            ["Rosinen"],
            ["Obstkorb"],
            ["Quitte", "quitten"],
            ["Kaki"],
            ["Physalis"],
            ["Boskoop"],
            ["Rhabarber"],
        ],
    ),
    (
        "Gemüse",
        [
            ["Tomaten", "tomate"],
            ["Kleine Tomaten", "kleine tomaten", "kleine tomate"],
            ["Kirschtomaten"],
            ["Datteltomaten"],
            ["Gurke", "gurken"],
            ["Salat"],
            ["Kopfsalat"],
            ["Feldsalat"],
            ["Rucola"],
            ["Eisbergsalat"],
            ["Paprika"],
            ["Spitzpaprika"],
            ["Zwiebel", "zwiebeln"],
            ["Frühlingszwiebel"],
            ["Schalotte"],
            ["Lauchzwiebel"],
            ["Knoblauch"],
            ["Kartoffel", "kartoffeln"],
            ["Süßkartoffel"],
            ["Möhren", "möhre", "karotte", "karotten"],
            ["Rote Bete", "rote bete", "rote rüben"],
            ["Radieschen"],
            ["Rettich"],
            ["Kohlrabi"],
            ["Weißkohl"],
            ["Rotkohl"],
            ["Wirsing"],
            ["Brokkoli"],
            ["Blumenkohl"],
            ["Rosenkohl"],
            ["Spitzkohl"],
            ["Spargel"],
            ["Pak Choi", "pak choi"],
            ["Spinat"],
            ["Mangold"],
            ["Avocado"],
            ["Pilze"],
            ["Champignons"],
            ["Steinpilze"],
            ["Pfifferlinge"],
            ["Kräuterseitlinge"],
            ["Ingwer"],
            ["Kurkuma frisch", "kurkuma frisch"],
            ["Kräuter"],
            ["Petersilie"],
            ["Schnittlauch"],
            ["Dill"],
            ["Basilikum"],
            ["Minze"],
            ["Lauch", "porree"],
            ["Zucchini", "zur rini", "zu knie"],
            ["Aubergine"],
            ["Fenchel"],
            ["Sellerie"],
            ["Maiskolben", "mais kolben"],
            ["Kürbis"],
            ["Hokkaido"],
            ["Topinambur"],
            ["Pastinake", "pastinaken"],
            ["Endiviensalat", "endivie"],
            ["Krautsalat", "weißkrautsalat"],
            ["Schwarzwurzel"],
            ["Petersilienwurzel"],
            ["Erdnüsse", "erdnuss", "peanuts"],
        ],
    ),
    (
        "Backwaren",
        [
            ["Brot"],
            ["Weißbrot"],
            ["Schwarzbrot"],
            ["Vollkornbrot"],
            ["Roggenbrot"],
            ["Dinkelbrot"],
            ["Mehrkornbrot"],
            ["Toastbrot"],
            ["Sandwichbrot"],
            ["Brötchen"],
            ["Semmel"],
            ["Kaisersemmel"],
            ["Laugenbrötchen"],
            ["Laugenstange"],
            ["Baguette"],
            ["Ciabatta"],
            ["Fladenbrot"],
            ["Pita"],
            ["Naan"],
            ["Croissant"],
            ["Plundergebäck"],
            ["Donut"],
            ["Muffin"],
            ["Kuchen"],
            ["Rührkuchen"],
            ["Käsekuchen"],
            ["Apfelkuchen"],
            ["Marmorkuchen"],
            ["Obstkuchen"],
            ["Frühstücksgebäck"],
            ["Knäckebrot"],
            ["Zwieback"],
            ["Toast"],
            ["Pumpernickel"],
            ["Stuten"],
            ["Rosinenbrot"],
        ],
    ),
    (
        "Salz&Gewürze",
        [
            ["Salz", "kochsalz", "tafelsalz"],
            ["Meersalz"],
            ["Fleur de Sel", "fleur de sel", "flörde-sell", "gutes salz"],
            ["Pfeffer"],
            ["Schwarzer Pfeffer", "schwarzer pfeffer"],
            ["Weißer Pfeffer", "weißer pfeffer"],
            ["Pfefferkörner"],
            ["Paprikapulver", "edelsüß", "rosenscharf"],
            ["Räucherpaprika", "rauchen paprika", "räuchern paprika"],
            ["Kurkuma"],
            ["Currypulver", "curry"],
            ["Garam Masala", "garam masala"],
            ["Zimt", "zimtstangen"],
            ["Oregano"],
            ["Majoran"],
            ["Basilikum getrocknet", "basilikum getrocknet"],
            ["Thymian"],
            ["Rosmarin"],
            ["Salbei"],
            ["Muskat", "muskatnuss"],
            ["Lorbeer", "lorbeerblatt"],
            ["Kardamom"],
            ["Nelken"],
            ["Piment"],
            ["Kümmel"],
            ["Kreuzkümmel Ganz", "kreuzkümmel"],
            ["Kreuzkümmel Gemahlen", "kreuzkümmel geh mal", "kreuzkümmel malen"],
            ["Fenchelsamen"],
            ["Anis"],
            ["Sternanis"],
            ["Chiliflocken"],
            ["Chilipulver"],
            ["Cayennepfeffer"],
            ["Knoblauchpulver"],
            ["Zwiebelpulver"],
            ["Kräuter der Provence", "kräuter der provence"],
            ["Italienische Kräuter", "italienische kräuter"],
            ["Gewürzmischung"],
            ["Grillgewürz"],
            ["Fischgewürz"],
            ["Geflügelgewürz"],
            ["Schwarzkümmel"],
            ["Liebstöckel"],
            ["Estragon"],
            ["Bohnenkraut"],
            ["Ras el Hanout", "ras el hanout"],
            ["Za'atar", "za'atar"],
        ],
    ),
    (
        "Backzutaten",
        [
            ["Mehl"],
            ["Weizenmehl"],
            ["Dinkelmehl"],
            ["Roggenmehl", "rocken mehl"],
            ["Vollkornmehl"],
            ["Mandelmehl"],
            ["Kokosmehl"],
            ["Brotmehl", "weizenmhel für brot", "weizen nähe zur brot"],
            ["Reismehl"],
            ["Roggen-Vollkorn Mehl", "roggen vollkorn mehrl", "rocken vollkorn mehl"],
            ["Type 405", "type 405"],
            ["Type 550", "type 550"],
            ["Zucker", "haushaltszucker"],
            ["Rohrzucker", "rohrohrzucker"],
            ["Puderzucker"],
            ["Vanillezucker"],
            ["Brauner Zucker", "brauner zucker"],
            ["Kandiszucker"],
            ["Hefe"],
            ["Trockenhefe"],
            ["Frische Hefe", "frische hefe"],
            ["Backpulver"],
            ["Natron"],
            ["Weinstein"],
            ["Vanille"],
            ["Vanilleschote"],
            ["Vanilleextrakt"],
            ["Vanillepudding-Pulver", "vanillepudding pulver"],
            ["Kakao", "kakaopulver"],
            ["Schokoraspeln"],
            ["Schokostückchen"],
            ["Marzipan"],
            ["Speisestärke", "maisstärke"],
            ["Guarkernmehl"],
            ["Lebensmittelfarbe"],
            ["Kuvertüre"],
            ["Fondant"],
            ["Backaroma", "back-aroma"],
            ["Rumaroma"],
            ["Zitronenschale"],
            ["Dr. Oetker", "dr oetker"],
            ["Ruf", "ruf backen"],
            ["Diamant Zucker", "diamant zucker"],
            ["Südzucker"],
            ["Gezuckerte Kondensmilch", "kondensmilch süß", "gezuckerte kondensmilch"],
            ["Süßstoff", "süßstofftabletten", "stevia", "candarel"],
        ],
    ),
    (
        "Aufschnitt",
        [
            ["Salami"],
            ["Salamisticks"],
            ["Pizzasalami"],
            ["Schinken"],
            ["Kochschinken"],
            ["Rohschinken"],
            ["Serranoschinken"],
            ["Parmaschinken"],
            ["Prosciutto"],
            ["Katenschinken"],
            ["Wurst"],
            ["Aufschnitt", "wurstaufschnitt"],
            ["Mortadella"],
            ["Lyoner"],
            ["Fleischwurst"],
            ["Bierschinken"],
            ["Bierwurst"],
            ["Leberwurst"],
            ["Teewurst"],
            ["Mettwurst"],
            ["Blutwurst"],
            ["Presskopf"],
            ["Sülze"],
            ["Chorizo"],
            ["Kabanossi"],
            ["Landjäger"],
            ["Schinkenwürfel"],
            ["Speckwürfel"],
            ["Speck"],
            ["Frühstücksspeck", "bacon"],
            ["Rügenwalder"],
            ["Gut & Günstig Wurst", "gut & günstig wurst"],
            ["Herta"],
            ["Wiltmann"],
            ["Homann"],
            ["Gutfried"],
            ["Ferrarini"],
            ["Pinkel"],
            ["Grützwurst"],
            ["Kasseler"],
            ["Krakauer"],
            ["Wienerwürstchen"],
            ["Frankfurter Würstchen", "frankfurter würstchen"],
            ["Weißwurst gekocht", "weißwurst gekocht"],
        ],
    ),
    (
        "Nudeln&Reis",
        [
            ["Nudeln", "trockene nudeln"],
            ["Spaghetti", "spaghettini"],
            ["Linguine"],
            ["Tagliatelle"],
            ["Fettuccine"],
            ["Penne"],
            ["Fusilli"],
            ["Rigatoni"],
            ["Farfalle"],
            ["Orecchiette"],
            ["Rotini"],
            ["Macaroni"],
            ["Lasagneblätter"],
            ["Cannelloni"],
            ["Vollkornnudeln"],
            ["Dinkelnudeln"],
            ["Eiernudeln"],
            ["Asia-Nudeln", "asia-nudeln"],
            ["Reis"],
            ["Langkornreis"],
            ["Rundkornreis"],
            ["Basmatireis"],
            ["Jasminreis"],
            ["Wildreis"],
            ["Milchreis"],
            ["Risottoreis", "arborio", "carnaroli"],
            ["Parboiled-Reis", "parboiled"],
            ["Couscous"],
            ["Bulgur"],
            ["Quinoa"],
            ["Hirse"],
            ["Polenta"],
            ["Graupen"],
            ["Barilla"],
            ["De Cecco", "de cecco"],
            ["Uncle Ben's", "uncle bens", "uncle ben's"],
            ["Oryza"],
            ["Rapunzel Reis", "rapunzel reis"],
            ["Tilda"],
            ["Buitoni"],
            ["Kartoffelbrei", "kartoffelpüree", "kartoffelpüree-pulver"],
            ["Kloßteig"],
            ["Kartoffelknödel"],
            ["Semmelknödel"],
        ],
    ),
    (
        "Tomatensoße",
        [
            ["Tomatensoße", "tomatensauce"],
            ["Passata", "passierte tomaten"],
            ["Gehackte Tomaten", "gehackte tomaten"],
            ["Stückige Tomaten", "stückige tomaten"],
            ["Tomatenmark", "doppeltkonzentriert"],
            ["Pizzasoße", "pizzasauce"],
            ["Arrabbiata"],
            ["Napoli"],
            ["Pasta-Sauce", "pasta sauce"],
            ["Pesto Rosso", "pesto rosso", "rote pasta sauce"],
            ["Tomaten-Basilikum-Soße", "tomaten-basilikum-soße"],
            ["Marinara"],
            ["Barilla Sauce", "barilla sauce"],
            ["Mutti"],
            ["Cirio"],
            ["Miti Tomaten", "miti tomaten"],
            ["Bertolli"],
            ["Knorr Fix", "knorr fix"],
        ],
    ),
    (
        "Konserven",
        [
            ["Konserve"],
            ["Dose"],
            ["Glas-Konserve", "glas konserve"],
            ["Bohnen in Dose", "bohnen in dose"],
            ["Weiße Bohnen", "weiße bohnen"],
            ["Schwarze Bohnen", "schwarze bohnen"],
            ["Kidneybohnen"],
            ["Kichererbsen", "kichererbsen dose"],
            ["Linsen", "linsen dose"],
            ["Mais", "mais dose", "meist"],
            ["Thunfisch in Dose", "thunfisch dose", "thunfisch in öl"],
            ["Sardinen in Dose", "sardinen dose", "ölsardinen"],
            ["Matjes"],
            ["Hering in Dose", "hering dose"],
            ["Sauerkraut im Glas", "sauerkraut glas"],
            ["Rotkohl im Glas", "rotkohl glas"],
            ["Ananas in Dose", "ananas dose"],
            ["Pfirsich in Dose", "pfirsich dose"],
            ["Kompott"],
            ["Bonduelle"],
            ["Hak"],
            ["Bratheringe"],
            ["Rollmops"],
            ["Apfelmus", "apfelkompott"],
        ],
    ),
    (
        "Delikatessen",
        [
            ["Delikatessen"],
            ["Antipasti", "antipasti-platte", "antipasti gemischt"],
            ["Oliven"],
            ["Schwarze Oliven", "schwarze oliven"],
            ["Grüne Oliven", "grüne oliven"],
            ["Kalamata-Oliven", "kalamata-oliven"],
            ["Gefüllte Oliven", "oliven gefüllt", "oliven mit knoblauch"],
            ["Olivenmix"],
            ["Pepperoni", "peperoni eingelegt", "peperonis", "feferoni"],
            ["Hummus", "klassischer hummus"],
            ["Rote-Bete-Hummus", "rote-bete-hummus"],
            ["Kapern", "kapernäpfel", "kapernbeeren"],
            ["Essiggurken"],
            ["Gewürzgurken"],
            ["Senfgurken"],
            ["Cornichons"],
            ["Silberzwiebeln"],
            ["Artischocken", "artischockenherzen"],
            ["Sardellen", "anchovis", "ölsardellen"],
            ["Getrocknete Tomaten", "getrocknete tomaten", "sundried tomaten"],
            ["Tomaten in Öl", "tomaten in öl"],
            ["Feta in Öl", "feta in öl"],
        ],
    ),
    (
        "Soßen",
        [
            ["Ketchup", "tomatenketchup", "catch up"],
            ["Currywurst-Soße", "currywurst-soße"],
            ["Mayonnaise"],
            ["Remoulade"],
            ["Senf", "zenf", "heinz"],
            ["Süßer Senf", "süßer senf"],
            ["Mittelscharfer Senf", "mittelscharfer senf"],
            ["Dijonsenf", "djionsenf"],
            ["Honigsenf"],
            ["Sojasoße"],
            ["Süß-Sauer-Soße", "süß-sauer-soße"],
            ["Barbecue-Soße", "barbecuesoße", "bbq"],
            ["Steak-Sauce", "steak-sauce"],
            ["HP Sauce", "hp sauce"],
            ["Pesto"],
            ["Pesto Verde", "pesto verde", "pesto genovese"],
            ["Hoisin"],
            ["Sweet Chili", "sweet chili"],
            ["Worcestershire-Sauce", "worcestershiresauce"],
            ["Tabasco"],
            ["Sriracha"],
            ["Tzatziki"],
            ["Maggi"],
            ["Knorr"],
            ["Miracel Whip", "miracel whip"],
            ["Thomy"],
            ["Hela"],
            ["Kraft"],
            ["Harissa", "harissapaste"],
            ["Tahini", "sesampaste"],
            ["Ajvar"],
            ["Mojo"],
            ["Chimichurri"],
        ],
    ),
    (
        "Aufstrich",
        [
            ["Aufstrich", "brotaufstrich"],
            ["Veganer Aufstrich", "veganer aufstrich"],
            ["Nutella"],
            ["Schokocreme", "nuss-nougat-creme", "schoko soße", "schokosoße", "schokogrem"],
            ["Nutoka"],
            ["Nudossi"],
            ["Erdnussbutter", "peanut butter"],
            ["Mandelmus"],
            ["Haselnussmus"],
            ["Marmelade"],
            ["Konfitüre"],
            ["Fruchtaufstrich"],
            ["Erdbeermarmelade", "erdbehrmammelade"],
            ["Aprikosenmarmelade"],
            ["Kirschkonfitüre"],
            ["Orangenmarmelade"],
            ["Pflaumenmus"],
            ["Honig", "blütenhonig", "akazienhonig", "waldhonig", "imkerhonig"],
            ["Manuka-Honig", "manuka honig"],
            ["Ahornsirup"],
            ["Agavendicksaft"],
            ["Rübensirup", "zuckerrübensirup"],
            ["Sirup"],
            ["Leberpastete"],
            ["Fischpaste"],
            ["Schwartau"],
            ["Zentis"],
            ["Rapunzel Mus", "rapunzel mus"],
        ],
    ),
    (
        "Essig&Öl",
        [
            ["Öl", "speiseöl", "salatöl"],
            ["Olivenöl", "natives olivenöl", "olivenöl extra vergine"],
            ["Sonnenblumenöl"],
            ["Rapsöl", "rapskernöl"],
            ["Leinöl"],
            ["Walnussöl"],
            ["Kürbiskernöl"],
            ["Kokosöl", "natives kokosöl"],
            ["Sesamöl", "geröstetes sesamöl"],
            ["Traubenkernöl"],
            ["Arganöl"],
            ["Avocadoöl"],
            ["Erdnussöl"],
            ["Distelöl"],
            ["Bratöl", "frittieröl"],
            ["Essig", "speiseessig", "tafelessig"],
            ["Weißweinessig"],
            ["Rotweinessig"],
            ["Balsamico", "balsamicoessig", "aceto balsamico", "balsamiku"],
            ["Weißer Balsamico", "weißer balsamico", "balsamico bianco"],
            ["Salatdressing", "joghurtdressing"],
            ["Balsamico-Dressing", "balsamico-dressing"],
            ["Essig-Öl-Dressing", "essig-öl-dressing"],
            ["Apfelessig"],
            ["Kräuteressig"],
            ["Branntweinessig"],
            ["Sherryessig"],
            ["Himbeeressig"],
            ["Obstessig"],
            ["Bertolli Olivenöl", "bertolli olivenöl"],
            ["Mazola"],
            ["Livio"],
        ],
    ),
    (
        "Fleisch",
        [
            ["Hähnchen"],
            ["Hähnchenbrust"],
            ["Hähnchenschenkel"],
            ["Hähnchenflügel"],
            ["Hühnerbrust"],
            ["Putenbrust"],
            ["Pute"],
            ["Ente"],
            ["Rindfleisch"],
            ["Rinderhack"],
            ["Rindergulasch"],
            ["Rinderfilet"],
            ["Rumpsteak"],
            ["Ribeye"],
            ["Schnitzel"],
            ["Wiener Schnitzel", "wiener schnitzel"],
            ["Schweinefleisch"],
            ["Schweinebauch"],
            ["Schweinefilet"],
            ["Kotelett"],
            ["Spareribs"],
            ["Lamm"],
            ["Lammkotelett"],
            ["Lammfilet"],
            ["Wild"],
            ["Rehrücken"],
            ["Wildschwein"],
            ["Leber", "rindsleber"],
            ["Innereien"],
            ["Burger Patty", "burger patty"],
            ["Frikadellen roh", "frikadellen roh"],
            ["Bratwurst roh", "bratwurst roh"],
        ],
    ),
    (
        "Eier",
        [
            ["Eier", "ei", "freilandeier", "bio-eier", "bodenhaltung", "aya"],
            ["Wachteleier"],
            ["10er Ei-Pack", "10er ei-pack"],
            ["Frühstücksei"],
        ],
    ),
    (
        "Fisch",
        [
            ["Lachs", "lachsfilet"],
            ["Räucherlachs", "graved lachs"],
            ["Thunfisch frisch", "thunfisch frisch", "thunfischsteak"],
            ["Garnelen", "scampi", "shrimps"],
            ["Kabeljau", "dorsch"],
            ["Seelachs", "alaska seelachs"],
            ["Forelle", "regenbogenforelle"],
            ["Rotbarsch"],
            ["Zander"],
            ["Fischfilet"],
            ["Matjes"],
            ["Hering frisch", "hering frisch"],
            ["Scholle"],
            ["Miesmuscheln", "muscheln"],
            ["Tintenfisch", "calamari frisch"],
            ["Kaviar", "lachskaviar"],
            ["Rogen", "fischrogen"],
            ["Frische Sardinen", "frische sardinen", "sardellen frisch"],
        ],
    ),
    (
        "Veganes",
        [
            ["Tofu", "naturtofu"],
            ["Räuchertofu", "geräucherter tofu"],
            ["Seidentofu"],
            ["Seitan"],
            ["Tempeh"],
            ["Lupinen"],
            ["Vegane Wurst", "vegane wurst"],
            ["Vegane Salami", "vegane salami"],
            ["Vegane Bratwurst", "vegane bratwurst"],
            ["Vegane Mortadella", "vegane mortadella"],
            ["Tofuwurst"],
            ["Vegane Butter", "vegane butter"],
            ["Veganer Käse", "veganer käse"],
            ["Vegane Mayo", "vegane mayo"],
            ["Vegane Sahne", "vegane sahne"],
            ["Veganer Aufschnitt", "veganer aufschnitt"],
            ["Veganes Schnitzel", "vegan schnitzel"],
            ["Veganer Burger", "veganer burger"],
            ["Fleischersatz"],
            ["Beyond Meat", "beyond meat"],
            ["Simply V", "simply v"],
            ["Vivera"],
            ["Like Meat", "like meat"],
            ["Rügenwalder Vegan", "rügenwalder vegan"],
            ["Hackfleisch", "hack flasch", "vegane hack",
             "veganes hack", "veganes hack flasch", "veganes huck", "wie garnessack"],
            ["Erbsenhack"],
            ["Sojahack", "sojagranulat"],
            ["Erbsenprotein"],
            ["Falafel", "falafelbällchen"],
            ["Linsenbällchen"],
            ["Vegane Bolognese", "vegane bolognese"],
            ["Chia Samen", "chia samen"],
            ["Nährhefe", "hefeflocken"],
        ],
    ),
    (
        "Milchprodukte",
        [
            ["Milch"],
            ["Vollmilch"],
            ["Fettarme Milch", "fettarme milch"],
            ["H-Milch", "h-milch", "haltbare milch"],
            ["Frischmilch"],
            ["Joghurt", "naturjoghurt"],
            ["Fruchtjoghurt"],
            ["Griechischer Joghurt", "griechischer joghurt"],
            ["Skyr"],
            ["Quark", "magerquark"],
            ["Kräuterquark"],
            ["Käse"],
            ["Schnittkäse"],
            ["Weichkäse"],
            ["Hartkäse"],
            ["Frischkäse"],
            ["Philadelphia"],
            ["Butter", "süßrahmbutter"],
            ["Halbfettbutter"],
            ["Sahne", "schlagsahne"],
            ["Schmand"],
            ["Crème Fraîche", "creme fraiche", "trämpf-räsch"],
            ["Saure Sahne", "saure sahne"],
            ["Buttermilch"],
            ["Kefir"],
            ["Mozzarella"],
            ["Büffelmozzarella"],
            ["Parmesan", "grana padano"],
            ["Feta", "schafskäse"],
            ["Ricotta"],
            ["Mascarpone"],
            ["Camembert"],
            ["Brie"],
            ["Gouda", "gauder"],
            ["Junger Gouda", "junger gouda", "junger gauder", "jungen gauder", "jungen gouda", "jungen goudauf"],
            ["Alter Gouda", "alter gouda", "alter gauder", "alten gouda", "alten goudauf"],
            ["Mittelalter Gouda", "mittelalter gouda", "mittelalter gauder", "mittelalten gouda", "mittelalten goudauf"],
            ["Edamer"],
            ["Emmentaler"],
            ["Cheddar"],
            ["Müller Milch", "müller milch"],
            ["Danone"],
            ["Ehrmann"],
            ["Landliebe"],
            ["Bärenmarke"],
            ["Weihenstephan"],
            ["Exquisa"],
            ["Almighurt"],
            ["Fruchtzwerge"],
            ["Räucherkäse", "rauchkäse"],
            ["Halloumi"],
            ["Streichkäse"],
            ["Kondensmilch"],
            ["Geriebener Mozzarella", "reibemozzarella", "geriebener mozzarella", "reiben-motorhalla"],
            ["Geriebener Parmesan", "geriebener parmesan"],
            ["Reibekäse", "geriebener käse"],
            ["Evaporierte Milch", "evaporierte milch"],
            ["Sahnesteif", "sahnefest"],
            ["Ayran"],
            ["Harzer Käse", "harzer käse"],
            ["Hafermilch", "haferdrink", "haferdrink barista"],
            ["Sojamilch", "sojadrink"],
            ["Sojajoghurt"],
            ["Mandelmilch", "mandeldrink"],
            ["Reisdrink"],
            ["Kokosdrink"],
            ["Kokosjoghurt"],
            ["Alpro"],
            ["Oatly"],
            ["Rude Health", "rude health"],
            ["Pflanzendrink", "pflanzlicher drink"],
        ],
    ),
    (
        "FrischeNudeln",
        [
            ["Frische Nudeln", "frische nudeln", "frische pasta"],
            ["Tortellini", "frische tortelloni"],
            ["Ravioli", "frische ravioli mit ricotta"],
            ["Tortelloni"],
            ["Gnocchi", "frische gnocchi"],
            ["Frische Tagliatelle", "frische tagliatelle"],
            ["Frische Lasagneplatten", "frische lasagneplatten"],
            ["Frische Spätzle", "frische spätzle"],
            ["Maultaschen", "schwäbische maultaschen"],
            ["Cappelletti", "frische cappelletti"],
        ],
    ),
    (
        "Alkohol",
        [
            ["Bier"],
            ["Pils"],
            ["Weizenbier", "weißbier"],
            ["Kölsch"],
            ["Altbier", "alt bier"],
            ["Lagerbier"],
            ["IPA", "ipa"],
            ["Stout"],
            ["Alkoholfreies Bier", "alkoholfreies bier"],
            ["Wein"],
            ["Rotwein"],
            ["Weißwein"],
            ["Roséwein", "rosewein"],
            ["Sekt"],
            ["Prosecco"],
            ["Crémant", "cremant"],
            ["Champagner"],
            ["Schaumwein"],
            ["Schnaps"],
            ["Korn"],
            ["Wodka"],
            ["Gin"],
            ["Rum"],
            ["Whisky", "bourbon", "scotch"],
            ["Tequila"],
            ["Absinth"],
            ["Likör", "kräuterlikör"],
            ["Eierlikör"],
            ["Obstler", "williamsbirne"],
            ["Sambuca"],
            ["Amaretto"],
            ["Cocktail"],
            ["Spritz", "aperol"],
            ["Campari"],
            ["Wermut"],
            ["Portwein"],
            ["Sherry"],
            ["Jägermeister"],
            ["Malibu"],
            ["Bacardi"],
            ["Smirnoff"],
            ["Jack Daniel's", "jack daniels"],
            ["Baileys"],
            ["Kahlúa", "kahlúa"],
            ["Hendrick's", "hendricks"],
            ["Tanqueray"],
            ["Beck's", "becks"],
            ["Krombacher"],
            ["Warsteiner"],
            ["Paulaner"],
            ["Augustiner"],
            ["Erdinger"],
            ["Veltins"],
            ["Apfelwein", "ebbelwoi"],
            ["Met", "honigwein"],
            ["Obstwein"],
            ["Cidre"],
            ["Bowle"],
            ["Glühwein"],
        ],
    ),
    (
        "Softdrinks",
        [
            ["Cola", "kohler"],
            ["Cola Light", "cola light"],
            ["Cola Zero", "cola zero"],
            ["Fanta"],
            ["Sprite"],
            ["Mezzo Mix", "mezzo mix"],
            ["Spezi"],
            ["Limonade"],
            ["Zitronenlimonade"],
            ["Mineralwasser"],
            ["Wasser", "stilles wasser"],
            ["Wasser mit Kohlensäure", "wasser mit kohlensäure"],
            ["Tafelwasser"],
            ["Saft", "obstsaft", "fruchtsaft"],
            ["Apfelsaft"],
            ["Orangensaft"],
            ["Multivitaminsaft"],
            ["Ananassaft", "ananas saft", "ananas soft"],
            ["Traubensaft"],
            ["Gemüsesaft", "tomatensaft"],
            ["Kirschsaft"],
            ["Rote-Bete-Saft", "rote bete saft", "rote-bete-saft"],
            ["Selleriesaft"],
            ["Trinkjoghurt"],
            ["Smoothie"],
            ["Schorle", "apfelschorle"],
            ["Tonic Water", "tonic water"],
            ["Bitter Lemon", "bitter lemon"],
            ["Ginger Ale", "ginger ale"],
            ["Ginger Beer", "ginger beer"],
            ["Energy Drink", "energy drink"],
            ["Red Bull", "red bull"],
            ["Iso-Getränk", "iso-getränk"],
            ["Eistee", "ice tea"],
            ["Sprudel", "sprudelwasser"],
            ["Pepsi"],
            ["Coca-Cola", "coca-cola", "coca cola"],
            ["7up", "7up"],
            ["Dr. Pepper", "dr pepper"],
            ["Schweppes"],
            ["Monster Energy", "monster energy"],
            ["Gatorade"],
            ["Capri-Sonne", "capri-sonne"],
            ["Lipton Ice Tea", "lipton ice tea"],
            ["Holundersirup"],
            ["Limettensaft"],
            ["Kombucha"],
            ["Ingwersirup"],
            ["Vita Malz", "vita malz", "malzbier"],
            ["Kokoswasser", "kokoswasser drink"],
        ],
    ),
    (
        "Coffee&Tea",
        [
            ["Kaffee"],
            ["Kaffeebohnen", "ganze bohnen"],
            ["Gemahlener Kaffee", "gemahlener kaffee", "filterkaffee"],
            ["Espresso"],
            ["Espressobohnen"],
            ["Espressopulver"],
            ["Kaffeepads"],
            ["Kaffeekapseln", "nespresso", "tassimo"],
            ["Instant-Kaffee", "instant kaffee", "löslicher kaffee"],
            ["Cappuccino-Pulver", "cappuccino pulver"],
            ["Milchkaffee-Pulver", "milchkaffee pulver"],
            ["Tee"],
            ["Schwarzer Tee", "schwarzer tee", "schwarztee"],
            ["Earl Grey", "earl grey"],
            ["English Breakfast", "english breakfast"],
            ["Darjeeling"],
            ["Assam"],
            ["Grüner Tee", "grüner tee", "grüntee"],
            ["Matcha"],
            ["Sencha"],
            ["Weißer Tee", "weißer tee"],
            ["Oolong"],
            ["Kräutertee"],
            ["Pfefferminztee"],
            ["Kamillentee"],
            ["Fencheltee"],
            ["Rooibos", "rooibostee"],
            ["Früchtetee"],
            ["Hagebuttentee"],
            ["Ingwertee"],
            ["Chai", "chai tee"],
            ["Yogi Tee", "yogi tee"],
            ["Wellnesstee"],
            ["Teebeutel"],
            ["Teedosen"],
            ["Erkältungstee"],
            ["Hustentee"],
            ["Halstee"],
            ["Salbeitee", "salbei tee"],
            ["Lindenblütentee"],
            ["Jacobs"],
            ["Dallmayr"],
            ["Tchibo"],
            ["Lavazza"],
            ["Illy"],
            ["Nescafé", "nescafé"],
            ["Melitta"],
            ["Starbucks"],
            ["Meßmer", "meßmer"],
            ["Teekanne"],
            ["Twinings"],
            ["Lipton Tee", "lipton tee"],
            ["Pukka"],
        ],
    ),
    (
        "Reinigungsmittel&Müll",
        [
            ["Spülmittel", "geschirrspülmittel"],
            ["Spülmaschinen-Tabs", "spülmaschinen-tabs"],
            ["Geschirrspülpulver"],
            ["Klarspüler"],
            ["Regeneriersalz"],
            ["Waschmittel", "vollwaschmittel"],
            ["Colorwaschmittel"],
            ["Feinwaschmittel"],
            ["Weichspüler"],
            ["Fleckenentferner"],
            ["Putzmittel", "allzweckreiniger"],
            ["Essigreiniger"],
            ["Badreiniger"],
            ["WC-Reiniger", "wc-reiniger"],
            ["Klobürste"],
            ["WC-Stein", "wc-stein"],
            ["Glasreiniger", "fensterreiniger"],
            ["Bodenreiniger"],
            ["Scheuermilch"],
            ["Stahlreiniger"],
            ["Müllbeutel", "müllsäcke"],
            ["Gefrierbeutel"],
            ["Frischhaltefolie"],
            ["Alufolie"],
            ["Backpapier"],
            ["Küchenrolle"],
            ["Putzlappen"],
            ["Schwamm", "spülschwamm"],
            ["Topfreiniger"],
            ["Toilettenpapier", "klopapier"],
            ["Papiertaschentücher"],
            ["Feuchttücher"],
            ["Pril"],
            ["Fairy"],
            ["Ariel"],
            ["Persil"],
            ["Lenor"],
            ["Calgonit"],
            ["Somat"],
            ["Mr. Proper", "mr proper"],
            ["Frosch"],
            ["Ecover"],
            ["Sagrotan"],
            ["Swiffer"],
            ["Domestos"],
            ["Tempo Taschentücher", "tempo taschentücher"],
            ["Zewa"],
            ["Edelstahlreiniger", "edelstahl-reiniger"],
            ["Handtüten", "müllbeutel handtüten"],
            ["1 Liter Tüten", "1 liter tüten", "müllbeutel 1 liter"],
            ["3 Liter Tüten", "3 liter tüten", "müllbeutel 3 liter"],
            ["Biomüllbeutel"],
        ],
    ),
    (
        "Zahnputz",
        [
            ["Zahnpasta", "zahncreme", "zahnpaste"],
            ["Zahnbürste"],
            ["Elektrische Zahnbürste", "elektrische zahnbürste"],
            ["Schallzahnbürste"],
            ["Zahnbürstenkopf", "aufsteckbürsten"],
            ["Interdentalbürsten"],
            ["Zahnseide", "dental floss"],
            ["Mundwasser", "mundspülung", "zahnspülung"],
            ["Munddusche"],
            ["Mundpflege"],
            ["Zungenreiniger"],
            ["Zahnreinigungstabletten"],
            ["Zahnaufheller"],
            ["Oral-B", "oral-b"],
            ["Colgate"],
            ["Sensodyne"],
            ["Elmex"],
            ["Parodontax"],
            ["Blend-a-med", "blend-a-med"],
            ["Signal"],
            ["Listerine"],
            ["Meridol"],
            ["Odol"],
        ],
    ),
    (
        "Kosmetik",
        [
            ["Creme"],
            ["Tagescreme"],
            ["Nachtcreme"],
            ["Gesichtscreme"],
            ["Augencreme"],
            ["Handcreme"],
            ["Fußcreme"],
            ["Bodylotion", "körperlotion"],
            ["Bodybutter"],
            ["Make-up", "make-up", "foundation"],
            ["Concealer"],
            ["Puder"],
            ["Blush"],
            ["Mascara", "wimperntusche"],
            ["Eyeliner"],
            ["Lidschatten"],
            ["Lippenstift"],
            ["Lipgloss"],
            ["Lippenpflege"],
            ["Deo", "deodorant", "antitranspirant"],
            ["Deospray"],
            ["Deoroller"],
            ["Rasierer", "einwegrasierer"],
            ["Rasierklingen"],
            ["Rasiergel"],
            ["Rasierschaum"],
            ["Aftershave"],
            ["Parfum"],
            ["Eau de Toilette", "eau de toilette"],
            ["Eau de Parfum", "eau de parfum"],
            ["Nagellack"],
            ["Nagellackentferner"],
            ["Nagelfeile"],
            ["Haarspray"],
            ["Haargel"],
            ["Haarwachs"],
            ["Stylingschaum"],
            ["Selbstbräuner"],
            ["Sonnencreme"],
            ["Nivea"],
            ["Dove"],
            ["L'Oréal", "loreal", "l'oréal"],
            ["Garnier"],
            ["Balea"],
            ["Isana"],
            ["CD Kosmetik", "cd kosmetik"],
            ["Axe"],
            ["Old Spice", "old spice"],
            ["Labello", "chapstick"],
            ["Maybelline"],
            ["Essence"],
            ["Catrice"],
            ["Rituals"],
        ],
    ),
    (
        "Seife&Shampoo",
        [
            ["Shampoo"],
            ["Anti-Schuppen-Shampoo", "anti-schuppen-shampoo"],
            ["Trockenshampoo"],
            ["Duschgel", "duschbad"],
            ["Duschöl"],
            ["Seife"],
            ["Handseife", "flüssigseife"],
            ["Haarseife"],
            ["Festes Shampoo", "festes shampoo"],
            ["Conditioner", "haarspülung", "spülung"],
            ["Intimwaschlotion", "Pussyspülung", "pussy spülung", "pussyzeug"],
            ["Haarkur", "leave-in"],
            ["Haarpflege"],
            ["Körperpflege"],
            ["Badezusatz", "badeöl", "schaumbad"],
            ["Head & Shoulders", "head & shoulders"],
            ["Schwarzkopf"],
            ["Pantene"],
            ["Herbal Essences", "herbal essences"],
            ["Syoss"],
            ["Garnier Shampoo", "garnier shampoo"],
            ["Elvital"],
            ["Alverde"],
            ["Kneipp"],
            ["Fa Duschgel", "fa duschgel"],
        ],
    ),
    (
        "Süßwaren",
        [
            ["Schokolade"],
            ["Milchschokolade"],
            ["Zartbitterschokolade"],
            ["Vollmilchschokolade"],
            ["Weiße Schokolade", "weiße schokolade"],
            ["Nougat"],
            ["Pralinen"],
            ["Schokoriegel"],
            ["Kit Kat", "kit kat"],
            ["Snickers"],
            ["Mars"],
            ["Twix"],
            ["Bounty"],
            ["Raffaello"],
            ["Ferrero"],
            ["Merci"],
            ["Lindor"],
            ["Gummibärchen", "haribo", "fruchtgummi"],
            ["Bonbons"],
            ["Lutscher"],
            ["Kekse", "butterkekse", "schokokekse"],
            ["Spekulatius"],
            ["Lebkuchen"],
            ["Müsliriegel"],
            ["Energieriegel"],
            ["Proteinriegel"],
            ["Süßigkeiten"],
            ["Kaugummi"],
            ["Pudding"],
            ["Vanillepudding"],
            ["Schokopudding"],
            ["Grießpudding"],
            ["Götterspeise", "wackelpudding"],
            ["Milka"],
            ["Ritter Sport", "ritter sport"],
            ["Lindt"],
            ["Toblerone"],
            ["After Eight", "after eight"],
            ["M&Ms", "m&ms"],
            ["Smarties"],
            ["Oreo"],
            ["Duplo"],
            ["Hanuta"],
            ["Manner Waffeln", "manner waffeln"],
            ["Kinderriegel"],
            ["Kinderschokolade"],
            ["Kinder Bueno", "kinder bueno"],
            ["Kinder Pingui", "kinder pingui"],
            ["Kinder Maxi King", "kinder maxi king"],
            ["Lakritz", "salzlakritz"],
            ["Marshmallows"],
            ["Marzipan-Süßigkeit", "marzipan-süßigkeit"],
            ["Marzipankartoffeln"],
            ["Schokoeier"],
            ["Halbmondkekse"],
            ["Amerikaner"],
            ["Russisch Brot", "russisch brot"],
            ["Cracker"],
            ["Reiswaffeln"],
        ],
    ),
    (
        "Snacks",
        [
            ["Snacks", "snack", "salzige snacks", "knabberzeug"],
            ["Chips", "kartoffelchips"],
            ["Salzstangen"],
            ["Popcorn"],
            ["Salzcracker", "knäckecracker"],
            ["Salzbrezeln", "brezeln"],
            ["Nüsse", "geröstete nüsse"],
            ["Salznüsse"],
            ["Studentenfutter"],
            ["Trockenfrüchte"],
            ["Pistazien", "salzpistazien"],
            ["Mandeln", "geröstete mandeln", "salzmandeln"],
            ["Cashews", "cashewkerne"],
            ["Walnüsse"],
            ["Haselnüsse"],
            ["Paranüsse"],
            ["Macadamia"],
            ["Pekannüsse"],
            ["Lays"],
            ["Pringles"],
            ["Doritos"],
            ["Funny Frisch", "funny frisch"],
            ["Ültje"],
            ["Seeberger"],
        ],
    ),
    (
        "Tiefgefrorenes",
        [
            ["Tiefkühl", "tiefkühlware", "tk-ware"],
            ["Tiefkühlpizza", "tk-pizza"],
            ["Speiseeis", "eiscreme"],
            ["Eis"],
            ["Schokoladeneis"],
            ["Vanilleeis", "vanille eis", "vermilter eis"],
            ["Fruchteis"],
            ["Magnum"],
            ["Ben & Jerry's", "ben & jerry's", "ben & jerrys", "ben and jerrys"],
            ["Häagen-Dazs", "häagen-dazs", "haagen dazs"],
            ["Mövenpick"],
            ["Langnese"],
            ["Nestlé Schöller", "nestlé schöller"],
            ["Fischstäbchen"],
            ["TK-Fisch", "tk-fisch"],
            ["TK-Lachs", "tk-lachs"],
            ["TK-Gemüse", "tk-gemüse", "gefrorenes gemüse"],
            ["TK-Erbsen", "tk-erbsen"],
            ["TK-Spinat", "tk-spinat"],
            ["TK-Bohnen", "tk-bohnen"],
            ["TK-Brokkoli", "tk-brokkoli"],
            ["TK-Mais", "tk-mais"],
            ["TK-Beeren", "tk-beeren", "gefrorene beeren", "tiefgefrorene beeren"],
            ["TK-Himbeeren", "tk-himbeeren", "gefrorene himbeeren", "tiefgefrorene himbeeren"],
            ["TK-Erdbeeren", "tk-erdbeeren", "gefrorene erdbeeren", "tiefgefrorene erdbeeren"],
            ["Gefrorene Blaubeeren", "gefrorene blaubeeren"],
            ["Gefrorenes Obst", "gefrorenes obst", "tiefgefrorenes obst"],
            ["Pommes", "tk-pommes"],
            ["Kroketten"],
            ["Rösti"],
            ["Blätterteig", "blätterteig tiefkühl", "blätterteig fertig"],
            ["Pizzateig", "pizzateig tk", "pizzateig tiefkühl", "fertigteig pizza tiefkühl"],
            ["TK-Kräuter", "tk-kräuter"],
            ["TK-Bratlinge", "tk-bratlinge"],
            ["Wagner Pizza", "wagner pizza"],
            ["Dr. Oetker Pizza", "dr oetker pizza"],
        ],
    ),
    (
        "Apotheke",
        [
            ["Ibuprofen"],
            ["Paracetamol"],
            ["Aspirin", "asprin"],
            ["Schmerzmittel", "schmerztabletten"],
            ["Kopfschmerztabletten"],
            ["Nasenspray", "abschwellendes nasenspray"],
            ["Hustensaft"],
            ["Hustenstiller"],
            ["Hustenlöser"],
            ["Halstabletten", "lutschtabletten"],
            ["Ricola"],
            ["Erkältungsmittel"],
            ["Wick"],
            ["Grippostad"],
            ["Vitamin D", "vitamin d"],
            ["Vitamin C", "vitamin c"],
            ["Magnesium"],
            ["Zink"],
            ["Multivitamin"],
            ["Eiweißpulver", "proteinpulver"],
            ["Elektrolyte"],
            ["Thermometer", "fieberthermometer"],
            ["Pflaster", "wundpflaster"],
            ["Verband", "mullbinde"],
            ["Wundsalbe", "wund- und heilsalbe"],
            ["Desinfektionsmittel", "händedesinfektion"],
            ["Ohrentropfen"],
            ["Augentropfen"],
            ["Kontaktlinsenflüssigkeit"],
            ["Bepanthen"],
            ["Voltaren"],
            ["Dolormin"],
            ["Octenisept"],
            ["Hansaplast"],
            ["Betaisodona"],
            ["Doppelherz"],
            ["Abtei"],
            ["Ratiopharm"],
            ["Wick MediNait", "wick medinait"],
            ["Insulin", "insolien"],
            ["Insulinspritze"],
            ["Blutzuckermessgerät"],
            ["Teststreifen"],
            ["Lanzetten"],
        ],
    ),
    (
        "Gartencenter&Baumarkt",
        [
            ["Blumenerde", "pflanzerde", "anzuchterde"],
            ["Blumentopf", "topf", "pflanztopf", "übertopf"],
            ["Samen", "saatgut"],
            ["Blumensamen"],
            ["Kräutersamen"],
            ["Tomatensamen"],
            ["Dünger", "düngemittel"],
            ["Blumendünger"],
            ["Pflanzendünger"],
            ["Gartendünger"],
            ["Rasendünger"],
            ["Schraube"],
            ["Nagel"],
            ["Dübel"],
            ["Haken"],
            ["Klebeband", "panzertape", "isolierband"],
            ["Silikon", "fugenmasse"],
            ["Farbe", "wandfarbe"],
            ["Lack"],
            ["Pinsel"],
            ["Rolle"],
            ["Abdeckfolie"],
            ["Schraubenzieher", "schraubendreher"],
            ["Akkuschrauber"],
            ["Bohrer"],
            ["Akku"],
            ["Batterien"],
            ["Knopfzellen"],
            ["9-Volt-Block", "9-volt-block"],
            ["Glühbirne", "led-lampe", "leuchtmittel"],
            ["Verlängerungskabel", "kabeltrommel"],
            ["Gartenschere"],
            ["Harke", "rechen"],
            ["Spaten"],
            ["Schaufel"],
            ["Gießkanne"],
            ["Schlauch"],
            ["Compo"],
            ["Neudorff"],
            ["Gardena"],
            ["Einhell"],
            ["Bosch Werkzeug", "bosch werkzeug"],
            ["Makita"],
            ["Pattex"],
            ["Uhu"],
            ["Tesa"],
            ["Ponal"],
        ],
    ),
    (
        "Asia",
        [
            ["Sojasoße", "soja sauce"],
            ["Fischsauce", "asiatische fischsauce", "nuoc mam"],
            ["Miso", "misopaste"],
            ["Wasabi", "wasabipaste"],
            ["Sushireis", "sushi reis"],
            ["Noriblätter", "noribätter", "nori"],
            ["Ramen", "instant-ramen"],
            ["Udon", "udonnudeln"],
            ["Soba", "sobanudeln"],
            ["Glasnudeln"],
            ["Reisnudeln"],
            ["Kokosmilch"],
            ["Kokoscreme"],
            ["Currypaste"],
            ["Rote Currypaste", "rote currypaste"],
            ["Grüne Currypaste", "grüne currypaste"],
            ["Gelbe Currypaste", "gelbe currypaste"],
            ["Limettenblätter", "kaffirlimette"],
            ["Thai-Basilikum", "thai basilikum", "thaibasilikum"],
            ["Shiitake", "shiitakepilze"],
            ["Bambussprossen"],
            ["Tempura"],
            ["Panko"],
            ["Süß-Sauer-Sauce", "süßsauer-soße", "sweet sour"],
            ["Reisessig"],
            ["Mirin"],
            ["Sake"],
            ["Kimchi"],
            ["Sriracha", "sriracha asia"],
            ["Hoisin Sauce", "hoisin sauce"],
            ["Kikkoman"],
            ["Lee Kum Kee", "lee kum kee"],
            ["Yutaka"],
            ["Blue Dragon", "blue dragon"],
            ["Mama Instant Noodles", "mama instant noodles"],
            ["Nissin"],
            ["Sushi-Ingwer", "sushi-ingwer", "gari", "eingelegter ingwer"],
            ["Misosuppe", "miso suppe"],
            ["Dashi"],
            ["Kombu"],
            ["Edamame"],
            ["Wakame"],
            ["Rotes Thai Curry", "rotes thai curry"],
            ["Grünes Thai Curry", "grünes thai curry"],
            ["Bonitoflocken", "katsuobushi", "bonito floppen"],
            ["Okonomiyaki"],
            ["Okonomiyaki Sauce", "okonomiyaki sauce"],
            ["Yakisoba"],
            ["Matcha-Pulver", "matcha pulver"],
        ],
    ),
    (
        "Mexiko",
        [
            ["Tortilla", "tortillas", "tot hier"],
            ["Tortilla-Wrap", "tortilla wrap"],
            ["Weizen-Tortilla", "weizen-tortilla"],
            ["Mais-Tortilla", "mais-tortilla"],
            ["Tortillachips", "tortilla-chips", "nachochips"],
            ["Wraps"],
            ["Tacoshells", "tacos"],
            ["Taco-Gewürz", "taco-gewürz"],
            ["Tacosauce"],
            ["Salsa", "salsa roja"],
            ["Salsa Verde", "salsa verde"],
            ["Guacamole"],
            ["Jalapeños", "chilischoten"],
            ["Chipotle"],
            ["Schwarze Bohnen mexikanisch", "schwarze bohnen mexikanisch"],
            ["Mais mexikanisch", "mais mexikanisch"],
            ["Burrito"],
            ["Fajita-Gewürz", "fajita-gewürz"],
            ["Fajita-Marinade", "fajita-marinade"],
            ["Nacho-Käse-Soße", "nacho-käse-soße"],
            ["Nachos"],
            ["Mole"],
            ["Enchilada-Soße", "enchilada-soße"],
            ["Old El Paso", "old el paso"],
            ["Santa Maria", "santa maria"],
            ["El Sabor", "el sabor"],
        ],
    ),
    (
        "Schreibwaren",
        [
            ["Kugelschreiber", "kuli"],
            ["Bleistift"],
            ["Buntstift"],
            ["Filzstift", "marker"],
            ["Textmarker"],
            ["Edding"],
            ["Fineliner"],
            ["Permanentmarker"],
            ["Radiergummi"],
            ["Anspitzer", "bleistiftspitzer"],
            ["Lineal"],
            ["Geodreieck"],
            ["Zirkel"],
            ["Schere"],
            ["Klebestift", "uhu klebestift"],
            ["Tesafilm", "klebeband schmal"],
            ["Heft", "schreibheft"],
            ["Rechenheft"],
            ["Collegeblock"],
            ["Schulheft"],
            ["Ringbuch"],
            ["Ordner", "aktenordner"],
            ["Schnellhefter"],
            ["Register"],
            ["Klarsichthülle", "klarsichthüllen"],
            ["Druckerpapier", "kopierpapier", "papier"],
            ["Notizblock"],
            ["Post-it", "post-it", "haftnotizen"],
            ["Briefumschlag", "umschlag"],
            ["Briefumschläge", "umschläge"],
            ["Briefmarken"],
            ["Geschenkpapier"],
            ["Geschenkband"],
            ["Schleife"],
            ["Kalender", "tischkalender", "wandkalender"],
            ["Stempel"],
            ["Stempelkissen"],
            ["Schulranzen"],
            ["Federmäppchen"],
            ["Tintenpatronen", "patronen tinte"],
            ["Füller"],
        ],
    ),
]
