"""Static category definitions.

Each entry is ``(name, anchor_terms)``. The classifier embeds the
category name and each anchor as separate vectors; an item's category
is decided by max cosine similarity across all of a category's anchors.

German compound words smuggle morphology — `"Mundspülung"` shares the
"spülung" stem with `"spülmittel"`, `"Eierlikör"` shares "Ei…" with
`"Eier"`. Sparse anchor lists let the wrong category win on those
surface signals. The lists below are deliberately thick: each category
has anchors for the obvious members *and* the compound variants the
user is likely to actually say. Add more whenever a compound
misclassifies.

Print order is decided elsewhere (Nix config); this file only declares
which categories exist and their semantic surface forms.
"""

CATEGORIES: list[tuple[str, list[str]]] = [
    (
        "Obst",
        [
            "apfel", "äpfel", "banane", "bananen", "birne", "birnen",
            "trauben", "weintrauben", "orange", "orangen", "mandarine",
            "clementine", "zitrone", "limette", "grapefruit",
            "erdbeere", "erdbeeren", "blaubeere", "heidelbeere",
            "himbeere", "brombeere", "johannisbeere", "stachelbeere",
            "kirsche", "kirschen", "pflaume", "pflaumen", "mirabelle",
            "ananas", "melone", "wassermelone", "honigmelone",
            "galiamelone", "mango", "papaya", "pfirsich", "nektarine",
            "aprikose", "kiwi", "feige", "granatapfel", "datteln",
            "rosinen", "obstkorb",
            "quitte", "quitten", "kaki", "physalis", "boskoop",
            "rhabarber", "stachelbeeren",
        ],
    ),
    (
        "Gemüse",
        [
            "tomate", "tomaten", "kirschtomaten", "datteltomaten",
            "gurke", "gurken", "salat", "kopfsalat", "feldsalat",
            "rucola", "eisbergsalat", "paprika", "spitzpaprika",
            "zwiebel", "zwiebeln", "frühlingszwiebel", "schalotte",
            "lauchzwiebel", "knoblauch", "kartoffel", "kartoffeln",
            "süßkartoffel", "möhre", "möhren", "karotte", "karotten",
            "rote bete", "radieschen", "rettich", "kohlrabi",
            "weißkohl", "rotkohl", "wirsing", "brokkoli", "blumenkohl",
            "rosenkohl", "spargel", "pak choi", "spinat", "mangold",
            "avocado", "pilze", "champignons", "steinpilze",
            "pfifferlinge", "kräuterseitlinge", "ingwer", "kurkuma frisch",
            "kräuter", "petersilie", "schnittlauch", "dill", "basilikum",
            "minze", "lauch", "porree", "zucchini", "aubergine",
            "fenchel", "sellerie", "mais kolben", "kürbis",
            "hokkaido",
            "topinambur", "pastinake", "pastinaken",
            "endiviensalat", "endivie", "krautsalat", "weißkrautsalat",
            "rote rüben", "schwarzwurzel", "petersilienwurzel",
            "erdnüsse", "erdnuss", "peanuts",
        ],
    ),
    (
        "Backwaren",
        [
            "brot", "weißbrot", "schwarzbrot", "vollkornbrot",
            "roggenbrot", "dinkelbrot", "mehrkornbrot", "toastbrot",
            "sandwichbrot", "brötchen", "semmel", "kaisersemmel",
            "laugenbrötchen", "laugenstange", "baguette", "ciabatta",
            "fladenbrot", "pita", "naan", "tortilla wrap",
            "croissant", "plundergebäck", "donut", "muffin",
            "kuchen", "rührkuchen", "käsekuchen", "apfelkuchen",
            "marmorkuchen", "obstkuchen", "bäcker", "frühstücksgebäck",
            "knäckebrot", "zwieback", "toast",
            "pumpernickel", "ciabatta-stangen",
            "fladen", "stuten", "rosinenbrot",
            "süßstoff", "süßstofftabletten", "stevia", "candarel",
        ],
    ),
    (
        "Salz&Gewürze",
        [
            "salz", "kochsalz", "meersalz", "fleur de sel",
            "tafelsalz", "pfeffer", "schwarzer pfeffer", "weißer pfeffer",
            "pfefferkörner", "paprikapulver", "edelsüß", "rosenscharf",
            "kurkuma", "currypulver", "curry", "garam masala", "zimt",
            "zimtstangen", "oregano", "majoran", "basilikum getrocknet",
            "thymian", "rosmarin", "salbei", "muskat", "muskatnuss",
            "lorbeer", "lorbeerblatt", "kardamom", "nelken",
            "piment", "kümmel", "fenchelsamen", "anis", "sternanis",
            "chiliflocken", "chilipulver", "cayennepfeffer",
            "knoblauchpulver", "zwiebelpulver", "kräuter der provence",
            "italienische kräuter", "gewürzmischung", "grillgewürz",
            "fischgewürz", "geflügelgewürz",
            "schwarzkümmel", "liebstöckel", "majoran", "estragon",
            "bohnenkraut", "ras el hanout", "za'atar",
        ],
    ),
    (
        "Backzutaten",
        [
            "mehl", "weizenmehl", "dinkelmehl", "roggenmehl",
            "vollkornmehl", "mandelmehl", "kokosmehl", "type 405",
            "type 550", "zucker", "haushaltszucker", "rohrzucker",
            "rohrohrzucker", "puderzucker", "vanillezucker",
            "brauner zucker", "kandiszucker", "hefe", "trockenhefe",
            "frische hefe", "backpulver", "natron", "weinstein",
            "vanille", "vanilleschote", "vanilleextrakt",
            "vanillepudding pulver", "kakao", "kakaopulver",
            "schokoraspeln", "schokostückchen", "marzipan",
            "speisestärke", "maisstärke", "guarkernmehl",
            "lebensmittelfarbe", "kuvertüre", "fondant",
            "back-aroma", "rumaroma", "zitronenschale",
            "dr oetker", "ruf backen", "diamant zucker",
            "südzucker",
            "kondensmilch süß", "gezuckerte kondensmilch",
        ],
    ),
    (
        "Charcuterie",
        [
            "salami", "salamisticks", "pizzasalami", "schinken", "kochschinken",
            "rohschinken", "serranoschinken", "parmaschinken",
            "prosciutto", "katenschinken", "wurst", "aufschnitt",
            "wurstaufschnitt", "mortadella", "lyoner",
            "fleischwurst", "bierschinken", "bierwurst",
            "leberwurst", "teewurst", "mettwurst", "blutwurst",
            "presskopf", "sülze", "chorizo", "kabanossi",
            "landjäger", "schinkenwürfel", "speckwürfel", "speck",
            "frühstücksspeck", "bacon",
            "rügenwalder", "gut & günstig wurst", "herta",
            "wiltmann", "homann", "gutfried", "ferrarini",
            "pinkel", "grützwurst", "kasseler", "krakauer",
            "wienerwürstchen", "frankfurter würstchen",
            "weißwurst gekocht",
        ],
    ),
    (
        "Nudeln&Reis",
        [
            "nudeln", "trockene nudeln", "spaghetti", "spaghettini",
            "linguine", "tagliatelle", "fettuccine", "penne",
            "fusilli", "rigatoni", "farfalle", "orecchiette",
            "rotini", "macaroni", "lasagneblätter", "cannelloni",
            "vollkornnudeln", "dinkelnudeln", "eiernudeln",
            "asia-nudeln", "reis", "langkornreis", "rundkornreis",
            "basmatireis", "jasminreis", "wildreis", "milchreis",
            "risottoreis", "arborio", "carnaroli", "parboiled",
            "couscous", "bulgur", "quinoa", "hirse", "polenta",
            "graupen",
            "barilla", "de cecco", "uncle bens", "uncle ben's",
            "oryza", "rapunzel reis", "tilda", "buitoni",
            "kartoffelbrei", "kartoffelpüree", "kartoffelpüree-pulver",
            "kloßteig", "kartoffelknödel", "semmelknödel",
        ],
    ),
    (
        "Tomatensoße",
        [
            "tomatensoße", "tomatensauce", "passata", "passierte tomaten",
            "gehackte tomaten", "stückige tomaten", "tomatenmark",
            "doppeltkonzentriert", "pizzasoße", "pizzasauce",
            "arrabbiata", "napoli", "pasta sauce", "pesto rosso",
            "rote pasta sauce", "tomaten-basilikum-soße",
            "marinara",
            "barilla sauce", "mutti", "cirio", "miti tomaten",
            "bertolli", "knorr fix",
        ],
    ),
    (
        "Konserven",
        [
            "konserve", "dose", "glas konserve", "bohnen in dose",
            "weiße bohnen", "schwarze bohnen", "kidneybohnen",
            "kichererbsen", "kichererbsen dose", "linsen dose",
            "mais dose", "thunfisch dose", "thunfisch in öl",
            "sardinen dose", "ölsardinen", "matjes", "hering dose",
            "sauerkraut glas", "rotkohl glas",
            "ananas dose", "pfirsich dose", "kompott",
            "bonduelle", "hak",
            "bratheringe", "rollmops",
            "apfelmus", "apfelkompott",
        ],
    ),
    (
        "Delikatessen",
        [
            "delikatessen", "antipasti", "antipasti-platte",
            "oliven", "schwarze oliven", "grüne oliven",
            "kalamata-oliven", "oliven gefüllt", "oliven mit knoblauch",
            "pepperoni", "peperoni eingelegt", "pepperoni eingelegt",
            "peperonis", "feferoni",
            "hummus", "rote-bete-hummus", "klassischer hummus",
            "kapern", "kapernäpfel", "kapernbeeren",
            "essiggurken", "gewürzgurken", "senfgurken",
            "cornichons", "silberzwiebeln",
            "artischocken", "artischockenherzen",
            "sardellen", "anchovis", "ölsardellen",
            "sundried tomaten", "getrocknete tomaten",
            "tomaten in öl", "feta in öl",
            "antipasti gemischt", "olivenmix",
        ],
    ),
    (
        "Soßen",
        [
            "ketchup", "tomatenketchup", "currywurst-soße",
            "mayonnaise", "remoulade", "senf", "süßer senf",
            "mittelscharfer senf", "djionsenf", "honigsenf",
            "sojasoße", "süß-sauer-soße", "barbecuesoße", "bbq",
            "steak-sauce", "hp sauce", "pesto", "pesto verde",
            "pesto genovese", "hoisin", "sweet chili",
            "worcestershiresauce", "tabasco", "sriracha",
            "salatdressing", "joghurtdressing",
            "balsamico-dressing", "essig-öl-dressing", "tzatziki",
            "heinz", "maggi", "knorr", "miracel whip",
            "thomy", "hela", "kraft",
            "harissa", "harissapaste", "tahini", "sesampaste",
            "ajvar", "mojo", "chimichurri",
            "zenf", "catch up",
        ],
    ),
    (
        "Aufstrich",
        [
            "aufstrich", "brotaufstrich", "veganer aufstrich",
            "nutella", "nuss-nougat-creme", "schokocreme",
            "nutoka", "nudossi",
            "erdnussbutter", "peanut butter", "mandelmus",
            "haselnussmus",
            "marmelade", "konfitüre", "fruchtaufstrich",
            "erdbeermarmelade", "aprikosenmarmelade",
            "kirschkonfitüre", "orangenmarmelade",
            "pflaumenmus",
            "honig", "blütenhonig", "akazienhonig", "waldhonig",
            "imkerhonig", "manuka honig",
            "ahornsirup", "agavendicksaft", "rübensirup",
            "zuckerrübensirup", "sirup",
            "leberpastete", "fischpaste", "tomatenmark süß",
            "schwartauer", "zentis", "rapunzel mus",
        ],
    ),
    (
        "Essig&Öl",
        [
            "öl", "speiseöl", "salatöl",
            "olivenöl", "natives olivenöl", "olivenöl extra vergine",
            "sonnenblumenöl", "rapsöl", "rapskernöl",
            "leinöl", "walnussöl", "kürbiskernöl",
            "kokosöl", "natives kokosöl",
            "sesamöl", "geröstetes sesamöl",
            "traubenkernöl", "arganöl", "avocadoöl",
            "erdnussöl", "distelöl", "bratöl", "frittieröl",
            "essig", "speiseessig", "tafelessig",
            "weißweinessig", "rotweinessig",
            "balsamico", "balsamicoessig", "aceto balsamico",
            "weißer balsamico", "balsamico bianco",
            "apfelessig", "kräuteressig", "branntweinessig",
            "sherryessig", "himbeeressig", "obstessig",
            "bertolli olivenöl", "mazola", "livio",
        ],
    ),
    (
        "Fleisch",
        [
            "hähnchen", "hähnchenbrust", "hähnchenschenkel",
            "hähnchenflügel", "hühnerbrust", "putenbrust", "pute",
            "ente", "rindfleisch", "rinderhack", "rindergulasch",
            "rinderfilet",
            "rumpsteak", "ribeye", "schnitzel", "wiener schnitzel",
            "schweinefleisch", "schweinebauch", "schweinefilet",
            "kotelett", "spareribs", "lamm", "lammkotelett",
            "lammfilet", "wild", "rehrücken", "wildschwein",
            "leber", "rindsleber", "innereien", "burger patty",
            "frikadellen roh", "bratwurst roh",
        ],
    ),
    (
        "Eier",
        [
            "ei", "eier", "freilandeier", "bio-eier", "bodenhaltung",
            "wachteleier", "größe m", "größe l", "10er ei-pack",
            "frühstücksei",
        ],
    ),
    (
        "Fisch",
        [
            "lachs", "lachsfilet", "räucherlachs", "graved lachs",
            "thunfisch frisch", "thunfischsteak", "garnelen",
            "scampi", "shrimps", "kabeljau", "dorsch", "seelachs",
            "alaska seelachs", "forelle", "regenbogenforelle",
            "rotbarsch", "zander", "fischfilet", "matjes",
            "hering frisch", "scholle", "miesmuscheln", "muscheln",
            "tintenfisch", "calamari frisch", "fisch frisch",
            "kaviar", "lachskaviar", "rogen", "fischrogen",
            "sardellen frisch", "frische sardinen",
        ],
    ),
    (
        "Veganes",
        [
            "tofu", "naturtofu", "räuchertofu", "geräucherter tofu",
            "seidentofu", "seitan", "tempeh", "lupinen",
            "vegane wurst", "vegane salami", "vegane bratwurst",
            "vegane butter", "veganer käse", "vegane mayo",
            "vegane sahne", "veganes hack", "fleischersatz",
            "veganer aufschnitt", "vegan schnitzel",
            "veganer burger", "haferdrink barista alternative",
            "beyond meat", "simply v", "vivera", "like meat",
            "rügenwalder vegan",
            "hackfleisch", "hack flasch", "vegane hack",
            "erbsenhack", "sojahack", "sojagranulat",
            "erbsenprotein", "veganes hack flasch",
            "vegane bratwurst", "vegane mortadella", "tofuwurst",
            "falafel", "falafelbällchen",
            "linsenbällchen", "vegane bolognese", "chia samen",
            "nährhefe", "hefeflocken",
        ],
    ),
    (
        "Milchprodukte",
        [
            "milch", "vollmilch", "fettarme milch", "h-milch",
            "haltbare milch", "frischmilch", "joghurt",
            "naturjoghurt", "fruchtjoghurt", "griechischer joghurt",
            "skyr", "quark", "magerquark", "kräuterquark",
            "käse", "schnittkäse", "weichkäse", "hartkäse",
            "frischkäse", "philadelphia", "butter", "süßrahmbutter",
            "halbfettbutter", "sahne", "schlagsahne", "schmand",
            "creme fraiche", "saure sahne", "buttermilch", "kefir",
            "mozzarella", "büffelmozzarella", "parmesan", "grana padano",
            "feta", "schafskäse", "ricotta", "mascarpone",
            "camembert", "brie", "gouda", "edamer", "emmentaler",
            "cheddar",
            "müller milch", "danone", "ehrmann", "landliebe",
            "bärenmarke", "weihenstephan", "exquisa", "almighurt",
            "fruchtzwerge",
            "junger gouda", "alter gouda", "mittelalter gouda",
            "rauchkäse", "räucherkäse",
            "halloumi", "streichkäse", "kondensmilch",
            "reibekäse", "reibemozzarella", "geriebener mozzarella",
            "geriebener parmesan", "geriebener käse",
            "evaporierte milch", "sahnesteif", "sahnefest",
            "kefir", "ayran", "harzer käse",
            "hafermilch", "haferdrink", "haferdrink barista",
            "sojamilch", "sojadrink", "sojajoghurt",
            "mandelmilch", "mandeldrink", "reisdrink", "kokosdrink",
            "kokosjoghurt", "alpro", "oatly", "rude health",
            "pflanzlicher drink", "pflanzendrink",
        ],
    ),
    (
        "FrischeNudeln",
        [
            "frische nudeln", "frische pasta", "tortellini",
            "ravioli", "tortelloni", "gnocchi", "frische gnocchi",
            "frische tagliatelle", "frische lasagneplatten",
            "frische ravioli mit ricotta", "frische pasta gefüllt",
            "frische spätzle",
            "maultaschen", "schwäbische maultaschen", "frische tortelloni",
            "frische cappelletti",
        ],
    ),
    (
        "Alkohol",
        [
            "bier", "pils", "weizenbier", "weißbier", "kölsch",
            "alt bier", "lagerbier", "ipa", "stout",
            "alkoholfreies bier", "wein", "rotwein", "weißwein",
            "rosewein", "lieblich", "trocken", "halbtrocken",
            "sekt", "prosecco", "cremant", "champagner", "schaumwein",
            "schnaps", "korn", "wodka", "gin", "rum",
            "whisky", "bourbon", "scotch", "tequila", "absinth",
            "likör", "kräuterlikör", "eierlikör", "obstler",
            "williamsbirne", "sambuca", "amaretto", "cocktail",
            "spritz", "aperol", "campari", "wermut", "portwein",
            "sherry",
            "jägermeister", "malibu", "bacardi", "smirnoff",
            "jack daniels", "baileys", "kahlúa", "hendricks",
            "tanqueray", "becks", "krombacher", "warsteiner",
            "paulaner", "augustiner", "erdinger", "veltins",
            "apfelwein", "ebbelwoi", "met", "honigwein",
            "obstwein", "cidre", "bowle", "glühwein",
        ],
    ),
    (
        "Softdrinks",
        [
            "cola", "cola light", "cola zero", "fanta", "sprite",
            "mezzo mix", "spezi", "limonade", "zitronenlimonade",
            "mineralwasser", "wasser", "stilles wasser",
            "wasser mit kohlensäure", "tafelwasser", "saft",
            "apfelsaft", "orangensaft", "multivitaminsaft",
            "ananassaft", "traubensaft", "gemüsesaft", "tomatensaft",
            "schorle", "apfelschorle", "tonic water", "bitter lemon",
            "ginger ale", "ginger beer", "energy drink", "red bull",
            "iso-getränk", "eistee", "ice tea",
            "ananassaft", "ananas saft", "ananas soft", "kirschsaft",
            "rote-bete-saft", "rote bete saft", "selleriesaft",
            "trinkjoghurt", "smoothie", "obstsaft", "fruchtsaft",
            "sprudel", "sprudelwasser", "tafelwasser",
            "pepsi", "coca-cola", "coca cola", "7up", "dr pepper",
            "schweppes", "monster energy", "gatorade", "capri-sonne",
            "lipton ice tea",
            "holundersirup", "limettensaft", "kombucha",
            "ingwersirup", "vita malz", "malzbier",
            "kokoswasser", "kokoswasser drink", "smoothie",
        ],
    ),
    (
        "Coffee&Tea",
        [
            "kaffee", "kaffeebohnen", "ganze bohnen",
            "gemahlener kaffee", "filterkaffee", "espresso",
            "espressobohnen", "espressopulver", "kaffeepads",
            "kaffeekapseln", "nespresso", "tassimo", "instant kaffee",
            "löslicher kaffee", "cappuccino pulver", "milchkaffee pulver",
            "tee", "schwarzer tee", "schwarztee", "earl grey",
            "english breakfast", "darjeeling", "assam",
            "grüner tee", "grüntee", "matcha", "sencha", "weißer tee",
            "oolong", "kräutertee", "pfefferminztee", "kamillentee",
            "fencheltee", "rooibos", "rooibostee", "früchtetee",
            "hagebuttentee", "ingwertee", "chai", "chai tee",
            "yogi tee", "wellnesstee", "teebeutel", "teedosen",
            "erkältungstee", "hustentee", "halstee",
            "salbeitee", "salbei tee", "lindenblütentee",
            "jacobs", "dallmayr", "tchibo", "lavazza", "illy",
            "nescafé", "melitta", "starbucks", "meßmer",
            "teekanne", "twinings", "lipton tee", "pukka",
        ],
    ),
    (
        "Reinigungsmittel&Müll",
        [
            "spülmittel", "geschirrspülmittel", "spülmaschinen-tabs",
            "geschirrspülpulver", "klarspüler", "regeneriersalz",
            "waschmittel", "vollwaschmittel", "colorwaschmittel",
            "feinwaschmittel", "weichspüler", "fleckenentferner",
            "putzmittel", "allzweckreiniger", "essigreiniger",
            "badreiniger", "wc-reiniger", "klobürste", "wc-stein",
            "glasreiniger", "fensterreiniger", "bodenreiniger",
            "scheuermilch", "stahlreiniger", "müllbeutel",
            "müllsäcke", "gefrierbeutel", "frischhaltefolie",
            "alufolie", "backpapier", "küchenrolle", "putzlappen",
            "schwamm", "spülschwamm", "topfreiniger",
            "toilettenpapier", "klopapier", "papiertaschentücher",
            "feuchttücher",
            "pril", "fairy", "ariel", "persil", "lenor",
            "calgonit", "somat", "mr proper", "frosch",
            "ecover", "sagrotan", "swiffer", "domestos",
            "tempo taschentücher", "zewa",
            "edelstahlreiniger", "edelstahl-reiniger",
            "handtüten", "1 liter tüten", "3 liter tüten",
            "müllbeutel handtüten", "müllbeutel 1 liter",
            "müllbeutel 3 liter", "biomüllbeutel",
        ],
    ),
    (
        "Zahnputz",
        [
            "zahnpasta", "zahncreme", "zahnpaste", "zahnbürste",
            "elektrische zahnbürste", "schallzahnbürste",
            "zahnbürstenkopf", "aufsteckbürsten",
            "interdentalbürsten", "zahnseide", "dental floss",
            "mundwasser", "mundspülung", "zahnspülung",
            "munddusche", "mundpflege", "zungenreiniger",
            "zahnreinigungstabletten", "zahnaufheller",
            "oral-b", "colgate", "sensodyne", "elmex",
            "parodontax", "blend-a-med", "signal", "listerine",
            "meridol", "odol",
        ],
    ),
    (
        "Kosmetik",
        [
            "creme", "tagescreme", "nachtcreme", "gesichtscreme",
            "augencreme", "handcreme", "fußcreme", "bodylotion",
            "bodybutter", "körperlotion", "make-up", "foundation",
            "concealer", "puder", "blush", "mascara", "wimperntusche",
            "eyeliner", "lidschatten", "lippenstift", "lipgloss",
            "lippenpflege", "deo", "deodorant", "antitranspirant",
            "deospray", "deoroller", "rasierer", "einwegrasierer",
            "rasierklingen", "rasiergel", "rasierschaum",
            "aftershave", "parfum", "eau de toilette", "eau de parfum",
            "nagellack", "nagellackentferner", "nagelfeile",
            "haarspray", "haargel", "haarwachs", "stylingschaum",
            "selbstbräuner", "sonnencreme",
            "nivea", "dove", "loreal", "l'oréal", "garnier",
            "balea", "isana", "cd kosmetik", "axe", "old spice",
            "labello", "chapstick", "maybelline", "essence",
            "catrice", "rituals",
        ],
    ),
    (
        "Seife&Shampoo",
        [
            "shampoo", "anti-schuppen-shampoo", "trockenshampoo",
            "duschgel", "duschbad", "duschöl", "seife",
            "handseife", "flüssigseife", "haarseife",
            "festes shampoo", "conditioner", "haarspülung",
            "spülung", "haarkur", "leave-in", "haarpflege",
            "körperpflege", "badezusatz", "badeöl", "schaumbad",
            "head & shoulders", "schwarzkopf", "pantene",
            "herbal essences", "syoss", "garnier shampoo",
            "elvital", "alverde", "kneipp", "fa duschgel",
        ],
    ),
    (
        "Süßwaren",
        [
            "schokolade", "milchschokolade", "zartbitterschokolade",
            "vollmilchschokolade", "weiße schokolade", "nougat",
            "pralinen", "schokoriegel", "kit kat", "snickers",
            "mars", "twix", "bounty", "raffaello", "ferrero",
            "merci", "lindor", "gummibärchen", "haribo",
            "fruchtgummi", "bonbons", "lutscher", "kekse",
            "butterkekse", "schokokekse", "spekulatius", "lebkuchen",
            "müsliriegel", "energieriegel", "proteinriegel",
            "süßigkeiten", "kaugummi",
            "pudding", "vanillepudding", "schokopudding",
            "grießpudding", "götterspeise", "wackelpudding",
            "milka", "ritter sport", "lindt", "toblerone",
            "after eight", "m&ms", "smarties", "oreo",
            "duplo", "hanuta", "manner waffeln",
            "kinderriegel", "kinderschokolade", "kinder bueno",
            "kinder pingui", "kinder maxi king",
            "lakritz", "salzlakritz", "marshmallows",
            "marzipan-süßigkeit", "marzipankartoffeln",
            "schokoeier", "halbmondkekse", "amerikaner",
            "russisch brot", "cracker", "reiswaffeln",
        ],
    ),
    (
        "Snacks",
        [
            "snack", "snacks", "salzige snacks", "knabberzeug",
            "chips", "kartoffelchips", "tortillachips", "tortilla-chips",
            "nachochips", "salzstangen", "popcorn", "salzcracker",
            "knäckecracker", "salzbrezeln", "brezeln",
            "nüsse", "salznüsse", "geröstete nüsse", "studentenfutter",
            "trockenfrüchte", "pistazien", "salzpistazien",
            "mandeln", "geröstete mandeln", "salzmandeln",
            "cashews", "cashewkerne", "walnüsse", "haselnüsse",
            "paranüsse", "macadamia", "pekannüsse",
            "lays", "pringles", "doritos", "funny frisch",
            "ültje", "seeberger",
        ],
    ),
    (
        "Tiefgefrorenes",
        [
            "tiefkühl", "tiefkühlpizza", "tiefkühlware", "tk-ware",
            "tk-pizza", "speiseeis", "eis", "eiscreme",
            "schokoladeneis", "vanilleeis", "magnum", "ben & jerry's",
            "haagen dazs", "fischstäbchen", "tk-fisch", "tk-lachs",
            "tk-gemüse", "tk-erbsen", "tk-spinat", "tk-bohnen",
            "tk-brokkoli", "tk-mais", "tk-beeren", "tk-himbeeren",
            "tk-erdbeeren", "pommes", "tk-pommes", "kroketten",
            "rösti", "blätterteig tiefkühl", "pizzateig tk",
            "tk-kräuter", "tk-bratlinge",
            "ben & jerrys", "ben and jerrys", "haagen dazs",
            "häagen-dazs", "magnum eis", "langnese", "mövenpick",
            "nestlé schöller", "wagner pizza", "dr oetker pizza",
            "pizzateig tiefkühl", "fertigteig pizza tiefkühl",
            "blätterteig fertig",
            "vanilleeis", "vanille eis", "schokoladeneis", "fruchteis",
            "gefrorene himbeeren", "gefrorene erdbeeren",
            "gefrorene blaubeeren", "gefrorene beeren",
            "gefrorenes obst", "gefrorenes gemüse",
            "tiefgefrorenes obst", "tiefgefrorene himbeeren",
            "tiefgefrorene erdbeeren", "tiefgefrorene beeren",
        ],
    ),
    (
        "Apotheke",
        [
            "ibuprofen", "paracetamol", "aspirin", "asprin",
            "schmerzmittel", "schmerztabletten", "kopfschmerztabletten",
            "nasenspray", "abschwellendes nasenspray", "hustensaft",
            "hustenstiller", "hustenlöser", "halstabletten",
            "lutschtabletten", "ricola", "erkältungsmittel",
            "wick", "grippostad", "vitamin d",
            "vitamin c", "magnesium", "zink", "multivitamin",
            "eiweißpulver", "proteinpulver", "elektrolyte",
            "thermometer", "fieberthermometer", "pflaster",
            "wundpflaster", "verband", "mullbinde", "wundsalbe",
            "wund- und heilsalbe", "desinfektionsmittel",
            "händedesinfektion", "ohrentropfen", "augentropfen",
            "kontaktlinsenflüssigkeit",
            "bepanthen", "voltaren", "dolormin", "octenisept",
            "hansaplast", "betaisodona", "doppelherz", "abtei",
            "ratiopharm", "wick medinait",
            "insulin", "insulinspritze", "blutzuckermessgerät",
            "teststreifen", "lanzetten",
        ],
    ),
    (
        "Gartencenter&Baumarkt",
        [
            "blumenerde", "pflanzerde", "anzuchterde", "topf",
            "blumentopf", "pflanztopf", "übertopf", "samen",
            "saatgut", "blumensamen", "kräutersamen",
            "tomatensamen", "dünger", "blumendünger",
            "pflanzendünger", "gartendünger", "rasendünger",
            "düngemittel", "schraube", "nagel", "dübel", "haken",
            "klebeband", "panzertape", "isolierband", "silikon",
            "fugenmasse", "farbe", "lack", "wandfarbe", "pinsel",
            "rolle", "abdeckfolie", "schraubenzieher",
            "schraubendreher", "akkuschrauber", "bohrer",
            "akku", "batterien", "knopfzellen", "9-volt-block",
            "glühbirne", "led-lampe", "leuchtmittel",
            "verlängerungskabel", "kabeltrommel", "gartenschere",
            "harke", "rechen", "spaten", "schaufel", "gießkanne",
            "schlauch",
            "compo", "neudorff", "gardena", "einhell", "bosch werkzeug",
            "makita", "pattex", "uhu", "tesa", "ponal",
        ],
    ),
    (
        "Asia",
        [
            "sojasoße", "soja sauce", "fischsauce", "asiatische fischsauce",
            "nuoc mam", "miso",
            "misopaste", "wasabi", "wasabipaste", "sushireis",
            "sushi reis", "noriblätter", "noribätter", "nori",
            "ramen", "instant-ramen", "udon", "udonnudeln",
            "sobanudeln", "soba", "glasnudeln", "reisnudeln",
            "kokosmilch", "kokoscreme", "currypaste",
            "rote currypaste", "grüne currypaste", "gelbe currypaste",
            "limettenblätter", "kaffirlimette", "thai basilikum",
            "thaibasilikum", "shiitake", "shiitakepilze",
            "bambussprossen", "tempura", "panko",
            "süßsauer-soße", "sweet sour", "reisessig", "mirin",
            "sake", "kimchi", "sriracha asia", "hoisin sauce",
            "kikkoman", "lee kum kee", "yutaka", "blue dragon",
            "mama instant noodles", "nissin",
            "sushi-ingwer", "gari", "eingelegter ingwer",
            "miso suppe", "dashi", "kombu", "edamame",
            "wakame", "rotes thai curry", "grünes thai curry",
            "bonitoflocken", "katsuobushi", "okonomiyaki",
            "okonomiyaki sauce", "yakisoba", "matcha pulver",
        ],
    ),
    (
        "Mexiko",
        [
            "tortilla", "tortillas", "weizen-tortilla",
            "mais-tortilla", "wraps", "tacoshells", "tacos",
            "taco-gewürz", "tacosauce", "salsa", "salsa roja",
            "salsa verde", "guacamole", "jalapeños", "chilischoten",
            "chipotle", "schwarze bohnen mexikanisch",
            "mais mexikanisch", "burrito", "fajita-gewürz",
            "fajita-marinade", "limetten", "nacho-käse-soße",
            "nachos", "tortilla-chips", "mole", "enchilada-soße",
            "old el paso", "santa maria", "el sabor",
        ],
    ),
    (
        "Schreibwaren",
        [
            "kugelschreiber", "kuli", "bleistift", "buntstift",
            "filzstift", "marker", "textmarker", "edding",
            "fineliner", "permanentmarker", "radiergummi",
            "anspitzer", "lineal", "geodreieck", "zirkel",
            "schere", "klebestift", "uhu klebestift",
            "tesafilm", "tesa", "klebeband schmal",
            "heft", "schreibheft", "rechenheft",
            "collegeblock", "schulheft", "ringbuch",
            "ordner", "aktenordner", "schnellhefter", "register",
            "klarsichthülle", "klarsichthüllen", "papier",
            "druckerpapier", "kopierpapier", "notizblock",
            "post-it", "haftnotizen", "haftnotizen-block",
            "umschlag", "briefumschlag", "umschläge",
            "briefumschläge", "briefmarken",
            "geschenkpapier", "geschenkband", "schleife",
            "kalender", "tischkalender", "wandkalender",
            "kuvert", "stempel", "stempelkissen",
            "schulranzen", "federmäppchen", "patronen tinte",
            "tintenpatronen", "füller", "bleistiftspitzer",
        ],
    ),
]
