{
  imports = [
    ./age.nix
    ./agenix.nix
    ./android-utils.nix
    ./auto-update.nix
    ./blocky.nix
    ./bluetooth.nix
    ./docker.nix
    ./eid.nix
    ./fail2ban.nix
    ./fish.nix
    ./greetd.nix
    ./gvfs.nix
    ./idagio.nix
    ./identities.nix
    ./keyring.nix
    ./ld.nix
    ./monit.nix
    ./nas.nix
    ./nicer-fonts.nix
    ./nvim.nix
    ./onlykey.nix
    ./plymouth.nix
    ./printers.nix
    ./qbittorrent.nix
    ./rsync.nix
    ./screensharing.nix
    ./snow.nix
    ./sound.nix
    ./static-hosting.nix
    ./steam-firewall.nix
    ./surfshark.nix
    ./suspend.nix
    ./wifi.nix
    ./wireguard.nix
    ./yubikey.nix
    ./zammad.nix
  ];
}
